// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserLoginResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *UserData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserLoginResponse) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserData struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coin                 int32    `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	Equips               []string `protobuf:"bytes,4,rep,name=equips,proto3" json:"equips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserData) GetEquips() []string {
	if m != nil {
		return m.Equips
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "proto.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "proto.UserLoginResponse")
	proto.RegisterType((*UserData)(nil), "proto.UserData")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x49, 0x9a, 0x44, 0xf4, 0x8a, 0xf8, 0xf0, 0x50, 0x2c, 0xa6, 0x60, 0x96, 0x4c, 0x1e,
	0xca, 0x1b, 0x44, 0x4c, 0x28, 0x03, 0x32, 0xe2, 0x01, 0x4c, 0x7d, 0xaa, 0x2c, 0xb5, 0xb6, 0x6b,
	0xbb, 0x88, 0xc7, 0x47, 0xb9, 0xb6, 0x52, 0x18, 0x3a, 0xdd, 0xd9, 0xbf, 0xff, 0x87, 0x6c, 0x58,
	0x6c, 0xfd, 0xc6, 0x3a, 0x19, 0xa2, 0xcf, 0x9e, 0xd5, 0x34, 0x84, 0x80, 0xfb, 0xaf, 0x84, 0x71,
	0x18, 0x89, 0xc2, 0xfd, 0x01, 0x53, 0x66, 0xb7, 0x50, 0x5a, 0xc3, 0x8b, 0xb6, 0xe8, 0x6a, 0x55,
	0x5a, 0x23, 0x06, 0x78, 0x98, 0x68, 0x52, 0xf0, 0x2e, 0x21, 0x63, 0x50, 0xad, 0xbd, 0xc1, 0x93,
	0x8c, 0x76, 0xf6, 0x02, 0x95, 0xd1, 0x59, 0xf3, 0xb2, 0x2d, 0xba, 0xc5, 0xea, 0xee, 0xd8, 0x24,
	0x47, 0xef, 0x9b, 0xce, 0x5a, 0x11, 0x14, 0xef, 0x70, 0x7d, 0xbe, 0x19, 0x43, 0x9c, 0xde, 0x21,
	0x19, 0xe6, 0x8a, 0xf6, 0x63, 0xb0, 0x75, 0x7c, 0x76, 0x0e, 0xb6, 0x8e, 0x2d, 0xa1, 0xc1, 0xfd,
	0xc1, 0x86, 0xc4, 0xab, 0x76, 0xd6, 0xcd, 0xd5, 0xe9, 0xb4, 0x1a, 0xa0, 0xf9, 0xc4, 0xf8, 0x83,
	0x91, 0xf5, 0x70, 0xf3, 0xef, 0x0d, 0x8f, 0x93, 0xf2, 0x29, 0x78, 0xba, 0x04, 0xc4, 0x55, 0xff,
	0x0c, 0x4b, 0xeb, 0xe5, 0x26, 0x86, 0xb5, 0xc4, 0x5f, 0xbd, 0x0b, 0x5b, 0x4c, 0x92, 0xbe, 0xac,
	0xaf, 0x69, 0x7c, 0x14, 0xdf, 0x0d, 0x99, 0x5f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x14, 0x13,
	0x55, 0x60, 0x4b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	// Sends a greeting
	LoginRequest(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginRequest, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) LoginRequest(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginRequest, error) {
	out := new(UserLoginRequest)
	err := c.cc.Invoke(ctx, "/proto.Server/LoginRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	// Sends a greeting
	LoginRequest(context.Context, *UserLoginRequest) (*UserLoginRequest, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_LoginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).LoginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/LoginRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).LoginRequest(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginRequest",
			Handler:    _Server_LoginRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
